### ISSUE TITLE
Seems highly incomplete; and possibly 99% fake data.

### ISSUE THREAD

**Issue by readnotify** [GeroldSetz/Mailinator-Domains#1]
At least 75% of the domains from the below master are not in this list:
https://raw.githubusercontent.com/FGRibreau/mailchecker/master/list.json

I run an email service with *massive* numbers of users (many millions of distinct email domains), and this list only matched two dozen domains: it looks like almost all those sha1 hashes are junk/rubbish and not real domains at all... they're just fake to make the list look big, when it's got almost nothing useful in it really.

**Comment by GeroldSetz** [comment]
Hi Mr. or Mrs. readnotify,

this is to notify that I just read your message ;-)

First of all: congratulations to your service which collects millions of domains - might be a good input for my project as well (see www.block-disposable-email.com).

Secondly, the list you found is for sure not fake - all domains are checked manually at the time when they appeared for the first time on my end. The hashed list includes about 2.000 alternative domains of **mailinator**. Some of them are not used very frequently for subscriptions. However, they are or have been used by mailinator. And this is what the list is dedicated to. To make it even more clear: the list does not include any domains of other disposable email services - that's why there is not so much overlap to the repository of @FGRibreau. To check your userbase against more than 10.000 domains of a variety of dea services [feel free to challenge us](https://www.block-disposable-email.com/cms/try/challenge-us/). 

The domains you found are published in hashed format in order not to disclose my asset and not to support using the domains for fake subscriptions. Anyway, it looks like I have to prove the content - so here is a list of 50 domains in plain text. Looking forward to get another statement from you.

boatloancalculators.info
mozazbnat.info
divaneganehosein.ir
adjun.info
aletaiblack.top
aliblue.top
ilcircolodelcibo.info
takup.info
fisiologia.info
achengred.top
achengyellow.top
barafa.gs
melis.ml
zhilin.info
goldminerptc.info
akesublue.top
anlublue.top
achengwhite.top
ankangblack.top
achengblue.top
ankangred.top
megamania.info
alipink.top
bnyzw.info
tennis-in-gifhorn.info
anluyellow.top
lebens-weise.info
test-server.xyz
lolsofunny.info
alired.top
grinn.ga
limon.cf
golubovi-bih.info
virtualmobileinfrastructure.us
ioio.eu
vaipe.ru
aletaiyellow.top
aliyellow.top
anqinggreen.top
eboise.com
zolotaya-mina.ru
ankangyellow.top
hnzjj.info
pheron.co
sfedora.ml
ankangpink.top
akesuwhite.top
net-cash.info
anqingwhite.top
aletaipink.top

(some of them might be outdated or not in use anymore)

**Comment by GeroldSetz** [comment]
Close issue due to missing response.

**Comment by lucidtheory** [comment]
would it be possible to merge the two lists together for a more complete list?

**Comment by GeroldSetz** [comment]
If I would get the list: yes. But it looks like "readnotify" is a fakeuser that just tries to speak bad of the list provided.
